channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.3.1
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - psutil==6.1.0
  - scikit-learn==1.3.0
  - scipy==1.14.1
name: mlflow-env
